### ISSUE TITLE
Kubernetes and Cilium](3-k8s-setup/README.md) link returns a 404 due to a missing README.md file

### ISSUE THREAD

**Issue by kerrd** [milagrofrost/proxmox-packer-cilium-bgp-cloudflare-zero-trust-openwrt-adguard-dns-lets-encrypt-k8s-homelab-of-doom#1]
Hi there.

Your readme is returning a 404 when you click on the 3-k8s-setup link due to a missing readme file.

3-k8s-setup
├── 1-initial-setup.md
├── 2-cilium-bgp.md
├── 3-cloudflare-operator.md
├── 4-cert-manager.md
├── 5-adguard-dns.md
└── files
    ├── adguard-dns-secret.sh
    ├── bgp.yaml
    ├── cloudflare-cert-manager.yaml
    ├── cloudflare-operator.yaml
    └── lb-pool.yaml

2 directories, 10 files

I'd open a merge request offering a markdown fix if there were the issue but with the file missing you would be best placed to fix this yourself.

**Comment by milagrofrost** [comment]
Thank you for catching that!  updated with ad9ba65880a4bd1142e8277c2e0620425deec858
